config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

RedmineApp::Application.routes.draw do
	match '/issues/plusgantt/show(:id)', :to => 'plusgantt#show', via: [:get], :as => 'plusgantt_show'
	match '/projects/issues/plusgantt/(:id)', :to => 'plusgantt#show', via: [:get, :post], :as => 'project_plusgantt'
	match '/projects/issues/plusgantt_dashboard/show/(:id)', :to => 'plusgantt_dashboard#show', via: [:get, :post], :as => 'plusgantt_dashboard_show'
	match '/projects/issues/plusgantt_dashboard/show_calculate/(:id)', :to => 'plusgantt_dashboard#show_calculate', via: [:get, :post], :as => 'plusgantt_dashboard_show_calculate'
	match '/projects/issues/plusgantt_dashboard/init_run/(:id)', :to => 'plusgantt_dashboard#init_run', via: [:get, :post], :as => 'plusgantt_dashboard_init_run'
	match '/projects/issues/plusgantt_dashboard/run/(:id)', :to => 'plusgantt_dashboard#run', via: [:get, :post], :as => 'plusgantt_dashboard_run'
	resources :pg_tracker_config
end

app/models/pg_tracker_config.rb
class PgTrackerConfig < ActiveRecord::Base
  unloadable
  belongs_to :tracker
  belongs_to :project
  #attr_accessor :id, :tracker_id, :project_id, :allow_time_log
  
  validates_presence_of :tracker_id, :allow_time_log
  
  validate :validate
  
  after_save :clearCache
  after_destroy :clearCache  
  
  def validate
    if self.id && self.project_id
		if PgTrackerConfig.where("id != ? AND project_id = ? AND tracker_id = ?", self.id, self.project_id, self.tracker_id).count > 0
			errors.add :project_id, :tracker_config_duplicated_error 
		end
	else
		if self.id && PgTrackerConfig.where("id != ? AND tracker_id = ?", self.id, self.tracker_id).count > 0
			errors.add :tracker_id, :tracker_config_duplicated_error 
		end
	end
	
	if self.id.blank?
		if self.project_id.blank?
			if PgTrackerConfig.where("tracker_id = ? and project_id is null", self.tracker_id).count > 0
				errors.add :tracker_id, :tracker_config_duplicated_error 
			end
		else
			if PgTrackerConfig.where("project_id = ? AND tracker_id = ?", self.project_id, self.tracker_id).count > 0
				errors.add :project_id, :tracker_config_duplicated_error 
			end
		end
	end
	
  end
  
private
  def clearCache
    Rails.cache.clear
  end
end

app/controllers/pg_tracker_config_controller.rb
class PgTrackerConfigController < ApplicationController
  
  before_action :check_edit_rights, :load_combo, only: [:edit, :update, :create, :destroy, :new]
  
  def show
	return index
  end
  
  def index
    @is_allowed = User.current.allowed_to_globally?(:config_tracker_timelog)
    @tracker_configs = PgTrackerConfig.all
  end
  
  def new
	@pg_tracker_config = PgTrackerConfig.new
  end
  
  def edit
    @pg_tracker_config = PgTrackerConfig.find(params[:id]) rescue nil 
  end    
  
  def update
	pg_tracker_config = PgTrackerConfig.find(params[:id]) rescue nil 
	respond_to do |format|
	  
		if params[:pg_tracker_config][:project_id]
			pg_tracker_config.project_id = params[:pg_tracker_config][:project_id]
		end
		pg_tracker_config.tracker_id = params[:pg_tracker_config][:tracker_id]
		pg_tracker_config.allow_time_log = params[:pg_tracker_config][:allow_time_log]
	  
	  if pg_tracker_config.save
		format.html { 
			flash[:notice] = 'Tracker Configuration was successfully updated.'
			redirect_to(:action => 'index')
		}
		format.xml  { head :ok }
	  else
		format.html {
		  flash[:error] = "<ul>" + pg_tracker_config.errors.full_messages.map{|o| "<li>" + o + "</li>" }.join("") + "</ul>" 
		  redirect_to(:action => 'edit') }
		format.xml  { render :xml => pg_tracker_config.errors, :status => :unprocessable_entity }
	  end
	end
  end
  
  def create
  
	tracker_config = PgTrackerConfig.new
	
	if params[:pg_tracker_config][:project_id] && !params[:pg_tracker_config][:project_id].blank?
		tracker_config.project_id = params[:pg_tracker_config][:project_id]
	end
	
	tracker_config.tracker_id = params[:pg_tracker_config][:tracker_id]
	tracker_config.allow_time_log = params[:pg_tracker_config][:allow_time_log]
	
	if tracker_config.save
		flash[:notice] = 'Tracker Configuration was successfully saved.'
		redirect_to action: 'index'
	else
		respond_to do |format| 
			format.html {
			  flash[:error] = "<ul>" + tracker_config.errors.full_messages.map{|o| "<li>" + o + "</li>" }.join("") + "</ul>"
			  redirect_to(:action => 'new') }
			format.api  { render_validation_errors(tracker_config) }
		end 
	end
  end
  
  def destroy
    @pg_tracker_config = PgTrackerConfig.find(params[:id]) rescue nil
    @pg_tracker_config.destroy
    flash[:notice] = 'Tracker Configuration was successfully deleted.'
    redirect_to(:action => 'index')
  end

private

	def load_combo
		@allow_options = [[l(:general_text_No), 0], [l(:general_text_Yes), 1]]
		@trackers = Tracker.pluck(:name, :id)
	end

  def check_edit_rights
    is_allowed = User.current.allowed_to_globally?(:config_tracker_timelog)
    if !is_allowed
      flash[:error] = translate 'no_right'
      redirect_to :action => 'index'
    end
  end
end

app/views/pg_tracker_config/_form.html.erb
<div class="splitcontentleft">
	<fieldset class="box tabular">
		<legend><%=  l(:tracker_config_title) %></legend>
		<p>
			<%= l(:field_project) %>
			<%= form.select :project_id, project_tree_options_for_select(Project.all.to_a, :selected => @pg_tracker_config.project, :include_blank => true, :required => false, disabled: disabled) %>    
		</p>
		<p>
			<%= l(:field_tracker) %>
			<%= form.select :tracker_id, options_for_select(@trackers, @pg_tracker_config.tracker_id), {:include_blank => false, :required => true, disabled: disabled} %>    
		</p>
		<p>
			<%= l(:label_tracker_config_allow) %>
			<%= form.select :allow_time_log, options_for_select(@allow_options, @pg_tracker_config.allow_time_log), {:include_blank => false, :required => true}%>
		</p>
	</fieldset>
</div>

app/views/pg_tracker_config/_show_list.html.erb
		<div class="autoscroll">
		<table class="list">
			<thead><tr>
				<th><%= l(:field_tracker) %></th>
				<th><%= l(:label_project) %></th>
				<th><%= l(:label_tracker_config_allow) %></th>
				<% if is_allowed %>			
					<th colspan="2"></th>
				<% end %>
			</tr></thead>
			<tbody>
		<% for tracker_config in tracker_configs -%>
			<tr class="<%= cycle("odd", "even") %>">
				<td><%= tracker_config.tracker.name.to_s %></td>
				<td><%= tracker_config.project.blank? ? '' : tracker_config.project.name %></td>	
				<td>
					<% if tracker_config.allow_time_log == 0 %>
						<%= l(:general_text_No) %>
					<% end %>
					<% if tracker_config.allow_time_log == 1 %>
						<%= l(:general_text_Yes) %>
					<% end %>
				</td>
				<% if is_allowed %>
	      			<td><%= link_to l(:button_edit), edit_pg_tracker_config_path(tracker_config) %></td>
	      			<td><%= link_to l(:button_delete), pg_tracker_config_path(tracker_config),
	              		method: :delete,
	              		data: { confirm: l(:text_are_you_sure) } %></td>
	            <% end %>

			</tr>
		<% end -%>	
			</tbody>
		</table>

app/views/pg_tracker_config/edit.html.erb
<% html_title(l(:tracker_config_title)) %>

<h2><%= l(:tracker_config_edit) %></h2>

<%= form_for @pg_tracker_config do |f| %>
	<%= render(partial: "form", locals: {form: f, disabled: true}) %>
	<div style = "float: none" class="splitcontentleft">
		<p>
			<%= f.submit l(:button_update)%>
			<%= link_to l(:button_cancel), :controller => 'pg_tracker_config', :action => "index" %>
		</p>
	</div>
<% end %>

app/views/pg_tracker_config/index.html.erb
<h1><%= l(:tracker_config_title)%></h1>

<%= link_to l(:label_new), new_pg_tracker_config_path, :class => 'icon icon-add' if @is_allowed %>
<p></p>
<% unless @tracker_configs.empty?%>	
	<%= render(partial: "show_list", locals: {tracker_configs: @tracker_configs, is_allowed: @is_allowed}) %>
<%end%>

app/views/pg_tracker_config/new.html.erb
<% html_title(l(:tracker_config_title)) %>

<h2><%= l(:tracker_config_new) %></h2>

<%= form_for :pg_tracker_config, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
	<%= render(partial: "form", locals: {form: f, disabled: false}) %>
	<div style = "float: none" class="splitcontentleft">
		<p>
			<%= f.submit l(:button_add)%>
			<%= link_to l(:button_cancel), :controller => 'pg_tracker_config', :action => "index" %>
		</p>
	</div>
<% end %>
  