config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

RedmineApp::Application.routes.draw do
	match '/issues/plusgantt/show(:id)', :to => 'plusgantt#show', via: [:get], :as => 'plusgantt_show'
	match '/projects/issues/plusgantt/(:id)', :to => 'plusgantt#show', via: [:get, :post], :as => 'project_plusgantt'
	match '/projects/issues/plusgantt_dashboard/show/(:id)', :to => 'plusgantt_dashboard#show', via: [:get, :post], :as => 'plusgantt_dashboard_show'
	match '/projects/issues/plusgantt_dashboard/show_calculate/(:id)', :to => 'plusgantt_dashboard#show_calculate', via: [:get, :post], :as => 'plusgantt_dashboard_show_calculate'
	match '/projects/issues/plusgantt_dashboard/init_run/(:id)', :to => 'plusgantt_dashboard#init_run', via: [:get, :post], :as => 'plusgantt_dashboard_init_run'
	match '/projects/issues/plusgantt_dashboard/run/(:id)', :to => 'plusgantt_dashboard#run', via: [:get, :post], :as => 'plusgantt_dashboard_run'
	resources :pg_tracker_config
end

app/controllers/plusgantt_dashboard_controller.rb
class PlusganttDashboardController < ApplicationController
  menu_item :plusgantt_dashboard

  before_action :init_cache, :only => [:init_run, :run]
  before_action :find_optional_project
  before_action :read_cache, :only => [:run]
  after_action  :write_cache, :only => [:init_run, :run]
  
  rescue_from Query::StatementInvalid, :with => :query_statement_invalid

  helper :issues
  helper :projects
  helper :queries
  include QueriesHelper
  helper :sort
  include SortHelper
  include PlusganttDashboardHelper

  def show
	Rails.logger.info("----------------show----------------------------")
	flash.clear
	@dashboard = Dashboard.new(params)
	@dashboard.project = @project
	session[:finished] = false
	session[:current] = nil
  end
  
  def show_calculate
	Rails.logger.info("----------------show_calculate----------------------------")
	@dashboard = Dashboard.new(params)
	@dashboard.project = @project
	if session[:current] && session[:finished]
		flash[:notice] = l(:label_issue_plural) + ": " + session[:current].to_s
	end
	session[:finished] = false
	session[:current] = nil
	@@cache.clear
	render :action => 'show'
  end
  
  def run
	Rails.logger.info("run.................")
	if request.post?
		result = process_tasks({:max_items => max_items_per_request, :max_time => 10.seconds}, session[:current])
		if result < 0
			flash[:error] = @dashboard.error unless @dashboard && @dashboard.error.blank?
			flash[:notice] = l(:label_issue_plural) + ": " + session[:current].to_s
			redirect_to plusgantt_dashboard_show_calculate_path(:project_id => @project)
		else
			if session[:finished]
				Rails.logger.info("recalculate_predecessors_end_date.................")
				if @dashboard.recalculate_predecessors_end_date(@predecessors) < 0
					flash[:error] = @dashboard.error unless @dashboard && @dashboard.error.blank?
				end
			end
			respond_to do |format|
				format.html {
					if session[:finished]
						redirect_to plusgantt_dashboard_show_calculate_path(:project_id => @project)
					else
						Rails.logger.info("redirect run.................")
						redirect_to plusgantt_dashboard_run_path(:project_id => @project)
					end
				}
				Rails.logger.info("js run.................")
				format.js
			end
		end
	end
  end
  
  def init_run
    session[:finished] = false
	@dashboard = Dashboard.new(params)
	@dashboard.project = @project
	if params[:user_action] && params[:user_action] == 'calculate'
		if @dashboard.validate_conf == 0
			@issues = @dashboard.project_issues(@project)
			@relations = @dashboard.load_relations(@issues)
			@predecessors = Hash.new []
			redirect_to plusgantt_dashboard_run_path(:project_id => @project)
		else
			@issues =  []
			flash[:error] = @dashboard.error unless @dashboard && @dashboard.error.blank?
			redirect_to plusgantt_dashboard_show_calculate_path(:project_id => @project)
		end
	else
		render :action => 'show'
	end
  end
  
  private
  def init_cache
	tmp_path = Rails.root.join('tmp')
	unless File.writable? tmp_path.to_s
		flash[:error] = "Temp-Dir: '" + tmp_path.to_s + "' is not writable!"
	end
	@@cache = ActiveSupport::Cache::FileStore.new(Rails.root.join('tmp','plusgantt_dashboard').to_s)
  end
  
  def read_cache
	@issues  = @@cache.read(:issues)
	@relations  = @@cache.read(:relations)
	@predecessors = @@cache.read(:predecessors)
  end
  
  def write_cache
    @@cache.write(:issues, @issues)
	@@cache.write(:relations, @relations)
	@@cache.write(:predecessors, @predecessors)
  end
  
  def process_tasks(options={}, resume_after)
	@dashboard = Dashboard.new(params)
	@dashboard.project = @project
	max_items = options[:max_items]
    max_time = options[:max_time]
    processed = 0
	position = 1
	if resume_after.nil?
		resume_after = 0
	end
    interrupted = false
    started_on = Time.now

    @issues.each do |issue|
      if (max_items && processed >= max_items) || (max_time && Time.now >= started_on + max_time)
        interrupted = true
        break
      end
      if position > resume_after
        #Do process
        processed += 1
		result = @dashboard.recalculate_issue_end_date(issue, @relations, @predecessors)
		if result[:processed] < 0
			return result[:processed]
		else
			@predecessors = result[:predecessors]
		end
      end
	  position += 1
    end

    if processed == 0 || !interrupted
      session[:finished] = true
	else
		session[:finished] = false
    end
	
	return session[:current] = position - 1
  end
  
	def max_items_per_request
		5
	end
end

app/views/plusgantt_dashboard/_progress.erb
				<tr>
					<td>
						<%
							content = ""
							style = ""
						%>
						<%= content_tag(:div, content.html_safe, :style => style, :class => 'plusgantt_progress_container') do %>
							<%
								content = ""
								style = ""
							%>
							<%= content_tag(:div, content.html_safe, :style => style, :id => 'progress_draw_area', :class => 'plusgantt_progress') %>
							<%
								content = l(:label_expected_progress)
								content += " " + @dashboard.get_expected_progress_text
							%>
							<%= content_tag(:div, content.html_safe, :style => style, :class => 'plusgantt_exp_progress') %>
						<% end %>
					</td>
					<td>
						<%
							content = ""
							style = ""
						%>
						<%= content_tag(:div, content.html_safe, :style => style, :class => 'plusgantt_hours_container') do %>
							<%
								content = "Horas"
								style = ""
							%>
							<%= content_tag(:div, content.html_safe, :style => style, :class => 'plusgantt_hours_right') %>
							<%
								content = @dashboard.get_total_hours_text
								style = ""
							%>
							<%= content_tag(:div, content.html_safe, :style => style, :class => 'plusgantt_hour_line total_budget') %>
							<%
								content = ""
								style = ""
							%>
							<%= content_tag(:div, content.html_safe, :style => style, :class => 'plusgantt_spacer') %>
							<%
								content = @dashboard.get_partial_budget_text
								style = "width: #{@dashboard.get_partial_budget_width}px;"
							%>
							<%= content_tag(:div, content.html_safe, :style => style, :class => 'plusgantt_hour_line partial_budget') %>
							<%
								content = ""
								style = ""
							%>
							<%= content_tag(:div, content.html_safe, :style => style, :class => 'plusgantt_spacer') %>
							<%
								content = @dashboard.get_consumed_text
								style = "width: #{@dashboard.get_consumed_width}px;"
								clss = "plusgantt_hour_line " + @dashboard.get_consumed_class
							%>
							<%= content_tag(:div, content.html_safe, :style => style, :class => clss) %>
						<% end %>
					</td>
				</tr>
				<tr>
					<td colspan = 2>
						<%= l(:label_control_date) %> <%= date_field_tag 'control_date', @dashboard.control_date %>
						<%= link_to_function l(:button_apply), '$("#user_action").val("report");$("#recalculate_form").submit()', :class => 'icon icon-checked' %>
					</td>
				</tr>

app/views/plusgantt_dashboard/run.html.erb
<h2><%= l(:label_plusgantt)%> - <%= @project.name %></h2> 

<div id="import-details">
  <div id="import-progress"><div id="progress-label">0 / <%= @issues.size.to_i %></div></div>
</div>

<%= javascript_tag do %>
$(document).ready(function() {
  $('#import-details').addClass('ajax-loading');
  $('#import-progress').progressbar({value: 0, max: <%= @issues.size.to_i %>});
  $.ajax({
    url: '<%= plusgantt_dashboard_run_path(:project_id => @project, :format => 'js') %>',
    type: 'post'
  });
});
<% end %>

app/views/plusgantt_dashboard/run.js.erb
$('#import-progress').progressbar({value: <%= session[:current].to_i %>});
$('#progress-label').text("<%= session[:current].to_i %> / <%= @issues.size.to_i %>");

<% if session[:finished] %>
	window.location.href='<%= plusgantt_dashboard_show_calculate_path(:project_id => @project) %>';
<% else %>
	$.ajax({
	  url: '<%= plusgantt_dashboard_run_path(:project_id => @project, :format => 'js') %>',
	  type: 'post'
	});
<% end %>

app/views/plusgantt_dashboard/show.html.erb
<% @dashboard.view = self %>
<h2><%= l(:label_plusgantt) %></h2>

<p><%= l(:label_help_recalculate_issue_end_date) %></p>

<% if !Plusgantt.calculate_end_date %>
	<%= link_to l(:label_calculate_issue_desactivated), '/settings/plugin/plus_gantt', :class => 'pglink' %>
	<%= link_to 'Settings', '/settings/plugin/plus_gantt', :class => 'pglink' %><br>
<% end %>

<% if Plusgantt.calculate_end_date %>
	<%= form_tag(plusgantt_dashboard_init_run_path(:project_id => @project), :id => 'recalculate_form') do %>
		<%= hidden_field_tag 'user_action', 'calculate' %>
		<table>
			<tbody>
				<tr>
					<td style="colspan: 2"><h3><%= @project.name %></h3></td>
				</tr>
				<tr>
					<td><%= @dashboard.render_project_detail %></td>
					<td><%= link_to_function l(:button_recalculate), '$("#recalculate_form").submit()', :class => 'icon icon-checked' %>
					| <%= link_to l(:label_plusgantt_chart), {:controller => "plusgantt", :action => "show", :project_id => @project} %>
					</td>
				</tr>
			</tbody>
		</table>
	<% end %>
	<% if @dashboard.has_subprojects %>
		<div class="projects box">
			<h3><%= l(:label_pgsubprojects) %></h3>
			<%= @dashboard.render_subprojects.html_safe %>
		</div>
	<% end %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'issues/sidebar' %>
<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'raphael' %>
  <%= javascript_include_tag :plusgantt_dashboard, :plugin => 'plus_gantt' %>
  <%= stylesheet_link_tag "plus_gantt.css", :plugin => "plus_gantt" %>
<% end %>

<%= javascript_tag do %>
  var progress_text = '<%= @dashboard.get_progress_text %>';
  var progress_value = '<%= @dashboard.get_progress_value %>';
  var color_line = '<%= @dashboard.get_color_line %>'
  $(document).ready(drawProgressHandler(progress_text, progress_value, color_line));
<% end %>