config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

RedmineApp::Application.routes.draw do
	match '/issues/plusgantt/show(:id)', :to => 'plusgantt#show', via: [:get], :as => 'plusgantt_show'
	match '/projects/issues/plusgantt/(:id)', :to => 'plusgantt#show', via: [:get, :post], :as => 'project_plusgantt'
	match '/projects/issues/plusgantt_dashboard/show/(:id)', :to => 'plusgantt_dashboard#show', via: [:get, :post], :as => 'plusgantt_dashboard_show'
	match '/projects/issues/plusgantt_dashboard/show_calculate/(:id)', :to => 'plusgantt_dashboard#show_calculate', via: [:get, :post], :as => 'plusgantt_dashboard_show_calculate'
	match '/projects/issues/plusgantt_dashboard/init_run/(:id)', :to => 'plusgantt_dashboard#init_run', via: [:get, :post], :as => 'plusgantt_dashboard_init_run'
	match '/projects/issues/plusgantt_dashboard/run/(:id)', :to => 'plusgantt_dashboard#run', via: [:get, :post], :as => 'plusgantt_dashboard_run'
	resources :pg_tracker_config
end

app/controllers/plusgantt_controller.rb
class PlusganttController < ApplicationController
  menu_item :plusgantt
  before_action :find_optional_project

  rescue_from Query::StatementInvalid, :with => :query_statement_invalid

  helper :plusgantt
  helper :issues
  helper :projects
  helper :queries
  include QueriesHelper
  helper :sort
  include SortHelper
  include Redmine::Export::PDF
  include PlusganttChartHelper

  def show
    @plusgantt = PlusganttChart.new(params, @project)
    @plusgantt.project = @project
	
    retrieve_query
    @query.group_by = nil
    @plusgantt.query = @query if @query.valid?

    basename = (@project ? "#{@project.identifier}-" : '') + 'plusgantt'

    respond_to do |format|
      format.html { render :action => "show", :layout => !request.xhr? }
      format.png  { send_data(@plusgantt.to_image, :disposition => 'inline', :type => 'image/png', :filename => "#{basename}.png") } if @plusgantt.respond_to?('to_image')
      format.pdf  { send_data(@plusgantt.to_pdf, :type => 'application/pdf', :filename => "#{basename}.pdf") }
    end
  end

end

app/helpers/plusgantt_helper.rb
module PlusganttHelper

  def gantt_zoom_link(gantt, in_or_out)
    case in_or_out
    when :in
      if gantt.zoom < 4
        link_to l(:text_zoom_in),
          {:params => request.query_parameters.merge(gantt.params.merge(:zoom => (gantt.zoom + 1)))},
          :class => 'icon icon-zoom-in'
      else
        content_tag(:span, l(:text_zoom_in), :class => 'icon icon-zoom-in').html_safe
      end

    when :out
      if gantt.zoom > 1
        link_to l(:text_zoom_out),
          {:params => request.query_parameters.merge(gantt.params.merge(:zoom => (gantt.zoom - 1)))},
          :class => 'icon icon-zoom-out'
      else
        content_tag(:span, l(:text_zoom_out), :class => 'icon icon-zoom-out').html_safe
      end
    end
  end
end

app/views/plusgantt/_issues_sidebar.html.erb
<% if User.current.allowed_to?(:view_plusgantt, @project, :global => true) && @project%>
	<h3><%= l(:label_plusgantt) %></h3>
	<%= '&nbsp;&nbsp;'.html_safe %>
	<%= link_to l(:label_pg_dashboard), {:controller => "plusgantt_dashboard", :action => "show", :project_id => @project} %><br>
	<%= '&nbsp;&nbsp;'.html_safe %>
	<%= link_to l(:label_plusgantt_chart), project_plusgantt_path(:project_id => @project) %><br>
	<% if User.current.allowed_to?(:config_tracker_timelog, @project, :global => true) %>
		<%= '&nbsp;&nbsp;'.html_safe %>
		<%= link_to l(:tracker_config_title), :controller => 'pg_tracker_config', :action => "index" %><br>
	<% end %>
	<h3></h3>
<% end %>

app/views/plusgantt/_project_show_right.html.erb
<% if User.current.allowed_to?(:view_plusgantt, @project, :global => true) %>
 <div class="projects box">
 <h3><%=l(:label_plusgantt)%></h3>
<%= link_to l(:label_pg_dashboard), {:controller => "plusgantt_dashboard", :action => "show", :project_id => @project} %> | 
<%= link_to l(:label_plusgantt_chart), project_plusgantt_path(:project_id => @project) %>	
</div>
<% end %>

app/views/plusgantt/show.html.erb
<% @plusgantt.view = self %>
<div class="contextual">
<% if !@query.new_record? && @query.editable_by?(User.current) %>
  <%= link_to l(:button_edit), edit_query_path(@query, :plusgantt => 1), :class => 'icon icon-edit' %>
  <%= delete_link query_path(@query, :plusgantt => 1) %>
<% end %>
</div>

<h2><%= l(:label_gantt) %></h2>

<%= form_tag(project_plusgantt_path(:project_id => @project), :id => 'query_form') do %>
<%= hidden_field_tag 'set_filter', '1' %>
<%= hidden_field_tag 'plusgantt', '1' %>

<p class="buttons">
<%= text_field_tag 'months', @plusgantt.months, :size => 2 %>
<%= l(:label_months_from) %> <%= select_month(@plusgantt.month_from, :prefix => "month", :discard_type => true) %>
<%= select_year(@plusgantt.year_from, :prefix => "year", :discard_type => true) %>
<%= hidden_field_tag 'zoom', @plusgantt.zoom %>
<%= l(:label_control_date) %> <%= date_field_tag 'control_date', @plusgantt.control_date %>
<%= l(:label_render_versions) %> <%= check_box_tag 'render_versions', '1', @plusgantt.render_versions %>
<%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
<%= link_to l(:button_clear), { :project_id => @project, :set_filter => 1 }, :class => 'icon icon-reload' %>
<% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
  <%= link_to_function l(:button_save), "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }').submit();", :class => 'icon icon-save' %>
<% end %>

<fieldset id="filters" class="collapsible collapsed">
  <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
  <div style="<%= @query.new_record? ? "" : "display: none;" %>">
    <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
  </div>
</fieldset>

<fieldset id="options" class="collapsible collapsed">
  <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
  <div style="display: none;">
    <table>
      <tr>
        <td>
          <fieldset>
            <legend><%= l(:label_related_issues) %></legend>
            <label for="draw_relations">
              <%= check_box 'query', 'draw_relations', :draw_relations => '0', :id => 'draw_relations' %>
              <% rels = [IssueRelation::TYPE_BLOCKS, IssueRelation::TYPE_PRECEDES] %>
              <% rels.each do |rel| %>
                <% color = PlusganttChartHelper::PlusganttChart::DRAW_TYPES[rel][:color] %>
                <%= content_tag(:span, '&nbsp;&nbsp;&nbsp;'.html_safe,
                                :style => "background-color: #{color}") %>
                <%= l(IssueRelation::TYPES[rel][:name]) %>
              <% end %>
            </label>
          </fieldset>
        </td>
      </tr>
    </table>
  </div>
</fieldset>

<div class="contextual">
  <%= gantt_zoom_link(@plusgantt, :in) %>
  <%= gantt_zoom_link(@plusgantt, :out) %>
</div>
</p>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
<%
  zoom = 1
  @plusgantt.zoom.times { zoom = zoom * 2 }

  subject_width = 330
  header_height = 18

  headers_height = header_height
  show_weeks = false
  show_days  = false
  show_day_num = false

  if @plusgantt.zoom > 1
    show_weeks = true
    headers_height = 2 * header_height
    if @plusgantt.zoom > 2
        show_days = true
        headers_height = 3 * header_height
        if @plusgantt.zoom > 3
          show_day_num = true
          headers_height = 4 * header_height
        end
    end
  end

  # Width of the entire chart
  g_width = ((@plusgantt.date_to - @plusgantt.date_from + 1) * zoom).to_i
  @plusgantt.render(:top => headers_height + 8,
                :zoom => zoom,
                :g_width => g_width,
                :subject_width => subject_width)
  g_height = [(20 * @plusgantt.number_of_rows) + 40, 280].max
  t_height = g_height + headers_height
%>

<% if @plusgantt.truncated %>
  <p class="warning"><%= l(:notice_gantt_chart_truncated, :max => @plusgantt.max_rows) %></p>
<% end %>

<table style="width:100%; border:0; border-collapse: collapse;">
<tr>
<td style="width:<%= subject_width %>px; padding:0px;">
  <%
    style = "position:relative;"
    style += "height: #{t_height}px;"
    style += "width: #{subject_width + 1}px;"
  %>
  <%= content_tag(:div, :style => style) do %>
    <%
      style = "right:-1px;"
      style += "width: #{subject_width}px;"
      style += "height: #{headers_height}px;"
	  text = '<h2>' + l(:label_plusgantt) + '</h2>'
    %>
    <%= content_tag(:div, text.html_safe, :style => style, :class => "plusgantt_hdr") %>
    <%
      style  = ""
      style += "width: #{subject_width}px;"
	  style += "height: #{g_height}px;"
    %>
    <%= content_tag(:div, "", :style => style, :class => "plusgantt_subject_area") do %>
		<%
			style  = ""
			style += "position: absolute;"
			style += "top: #{headers_height + 8}px;"
		%>
		<%= content_tag(:div, :id => 'div_subjects', :style => style, :class => "plusgantt_subjects") do %>
		  <%= @plusgantt.subjects.html_safe %>
		<% end %>
	<% end %>
  <% end %>
</td>

<td>
<div style="position:relative;right:1px;height:<%= t_height%>px;overflow:-webkit-paged-x;" id="gantt_area">
<%
  style = "width: #{g_width - 1}px;"
  style += "height: #{headers_height}px;"
%>
<%= content_tag(:div, '&nbsp;'.html_safe, :style => style, :class => "plusgantt_hdr") %>

<% ###### Months headers ###### %>
<%
  month_f = @plusgantt.date_from
  left = 0
  height = (show_weeks ? header_height - 1 : g_height)
%>
<% @plusgantt.months.times do %>
  <%
    width = (((month_f >> 1) - month_f) * zoom - 1).to_i
    style = "left: #{left}px;"
    style += "width: #{width}px;"
    style += "height: #{height}px;"
  %>
  <%= content_tag(:div, :style => style, :class => "plusgantt_hdr_col") do %>
    <%= link_to "#{month_f.year}-#{month_f.month}",
                @plusgantt.params.merge(:year => month_f.year, :month => month_f.month),
                :title => "#{month_name(month_f.month)} #{month_f.year}" %>
  <% end %>
  <%
    left = left + width + 1
    month_f = month_f >> 1
  %>
<% end %>

<% ###### Weeks headers ###### %>
<% if show_weeks %>
  <%
    left = 0
    height = (show_days ? header_height - 1 : g_height - header_height - 1)
  %>
  <% if @plusgantt.date_from.cwday == 1 %>
    <%
      # @date_from is monday
      week_f = @plusgantt.date_from
    %>
  <% else %>
    <%
      # find next monday after @date_from
      week_f = @plusgantt.date_from + (7 - @plusgantt.date_from.cwday + 1)
      width = (7 - @plusgantt.date_from.cwday + 1) * zoom - 1
      style = "left: #{left}px;"
      style += "top: #{header_height+1}px;"
      style += "width: #{width}px;"
      style += "height: #{height}px;"
    %>
    <%= content_tag(:div, '&nbsp;'.html_safe,
                    :style => style, :class => "plusgantt_hdr_col") %>
    <% left = left + width + 1 %>
  <% end %>
  <% while week_f <= @plusgantt.date_to %>
    <%
      width = ((week_f + 6 <= @plusgantt.date_to) ?
                  7 * zoom - 1 :
                  (@plusgantt.date_to - week_f + 1) * zoom - 1).to_i
      style = "left: #{left}px;"
      style += "top: #{header_height+1}px;"
      style += "width: #{width}px;"
      style += "height: #{height}px;"
    %>
    <%= content_tag(:div, :style => style, :class => "plusgantt_hdr_col") do %>
      <%= content_tag(:small) do %>
        <%= week_f.cweek if width >= 16 %>
      <% end %>
    <% end %>
    <%
      left = left + width + 1
      week_f = week_f + 7
    %>
  <% end %>
<% end %>

<% ###### Day numbers headers ###### %>
<% if show_day_num %>
  <%
    left = 0
    height = header_height
	top = (2 * header_height) + 1
    wday = @plusgantt.date_from.cwday
    day_num = @plusgantt.date_from
  %>
  <% (@plusgantt.date_to - @plusgantt.date_from + 1).to_i.times do %>
    <%
      width =  zoom - 1
      style = "left: #{left}px;"
      style += "top: #{top}px;"
      style += "width: #{width}px;"
      style += "height: #{height}px;"
      clss = "plusgantt_hdr_col"
      clss << " nwday" if @plusgantt.non_working_week_days.include?(wday)
    %>
    <%= content_tag(:div, :style => style, :class => clss) do %>
      <%= day_num.day %>
    <% end %>
    <%
     left = left + width+1
     day_num = day_num + 1
     wday = wday + 1
     wday = 1 if wday > 7
    %>
  <% end %>
<% end %> 

<% ###### Days headers ####### %>
<% if show_days %>
  <%
    left = 0
	if show_day_num
		height = g_height - (3 * header_height) - 1
		top = (3 * header_height) + 1
	else
		height = g_height - (2 * header_height) - 1
		top = (2 * header_height) + 1
	end
    wday = @plusgantt.date_from.cwday
  %>
  <% (@plusgantt.date_to - @plusgantt.date_from + 1).to_i.times do %>
    <%
      width =  zoom - 1
      style = "left: #{left}px;"
      style += "top: #{top}px;"
      style += "width: #{width}px;"
      style += "height: #{height}px;"
      clss = "plusgantt_hdr_col"
      clss << " nwday" if @plusgantt.non_working_week_days.include?(wday)
    %>
    <%= content_tag(:div, :style => style, :class => clss) do %>
      <%= day_letter(wday) %>
    <% end %>
    <%
      left = left + width + 1
      wday = wday + 1
      wday = 1 if wday > 7
    %>
  <% end %>
<% end %>

  <%
    style = "position: absolute;"
    style += "top: #{headers_height + 8}px;"
	%>
 <%= content_tag(:div, :id => 'div_lines', :style => style) do %>
      <%= @plusgantt.lines.html_safe %>
 <% end %>


<% ###### Today red line (excluded from cache) ###### %>
<% if User.current.today >= @plusgantt.date_from and User.current.today <= @plusgantt.date_to %>
  <%
    today_left = (((User.current.today - @plusgantt.date_from + 1) * zoom).floor() - 1).to_i
    style = "position: absolute;"
    style += "height: #{g_height}px;"
    style += "top: #{headers_height + 1}px;"
    style += "left: #{today_left}px;"
    style += "width:10px;"
    style += "border-left: 1px dashed red;"
  %>
  <%= content_tag(:div, '&nbsp;'.html_safe, :style => style, :id => 'today_line') %>
<% end %>

<% ###### Fecha de Control ###### %>
<%
	fecha_control = @plusgantt.control_date
    control_left = (((fecha_control.to_date - @plusgantt.date_from + 1) * zoom).floor() - 1).to_i
    style = "position: absolute;"
    style += "height: #{g_height}px;"
    style += "top: #{headers_height + 1}px;"
    style += "left: #{control_left}px;"
    style += "width:10px;"
    style += "border-left: 1px dashed black;"
%>
 <%= content_tag(:div, '&nbsp;'.html_safe, :style => style, :id => 'corte') %>

<%
  style = "height: #{g_height}px;"
  style += "top: #{headers_height + 1}px;"
  style += "width: #{g_width - 1}px;"
  css_class = ""
  css_class = "plusgantt_area"
%>
<%= content_tag(:div, '', :style => style, :id => "gantt_draw_area", :class => css_class) %>
</div>
</td>
</tr>
</table>

<table style="width:100%">
<tr>
  <td style="text-align:left;">
    <%= link_to("\xc2\xab " + l(:label_previous), {:params => request.query_parameters.merge(@plusgantt.params_previous)}, :accesskey => accesskey(:previous)) %>
  </td>
  <td style="text-align:right;">
    <%= link_to(l(:label_next) + " \xc2\xbb", {:params => request.query_parameters.merge(@plusgantt.params_next)}, :accesskey => accesskey(:next)) %>
  </td>
</tr>
</table>

<% other_formats_links do |f| %>
  <%= f.link_to 'PDF', {:url => request.query_parameters.merge(@plusgantt.params)} %>
  <%= f.link_to('PNG', {:url => request.query_parameters.merge(@plusgantt.params)}) if @plusgantt.respond_to?('to_image') %>
<% end %>
<% end # query.valid? %>

<% content_for :sidebar do %>
  <%= render :partial => 'issues/sidebar' %>
<% end %>

<% html_title(l(:label_gantt)) -%>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'raphael' %>
  <%= javascript_include_tag :plusgantt, :plugin => 'plus_gantt' %>
  <%= stylesheet_link_tag "plus_gantt.css", :plugin => "plus_gantt" %>
<% end %>

<%= javascript_tag do %>
  var issue_relation_type = <%= raw PlusganttChartHelper::PlusganttChart::DRAW_TYPES.to_json %>;
  $(document).ready(drawGanttHandler);
  $(window).resize(drawGanttHandler);
  $(function() {
    $("#draw_relations").change(drawGanttHandler);
  });
<% end %>